version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: 
          name: Install pytests
          command: |
            pip install pytest
      - run:
        name: Run tests
        command: |
          pytest test.py

