version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: pip install --user pytest
      - run: PATH=/home/circleci/.local/bin:$PATH
      - run: pytest test.py
